export default {
  build: {
    html: 'build',
    scripts: 'build/media/js/',
    styles: 'build/media/css/',
    images: 'build/media/images/',
    fonts: 'build/media/fonts/',
    sprites: 'build/media/images/sprites/',
    svg: 'build/media/svg/',
    videos: 'build/media/video/',
  },
  src: {
    templates: './src/media',
    nunj: 'src/media/templates/pages/**/*.nunj',
    scripts: 'src/media/js/index.js',
    styles: 'src/media/sass/screen.scss',
    images: 'src/media/images/**/*.*',
    imagesInline: 'src/media/images/inline/',
    fonts: 'src/media/fonts/**/*.*',
    sprites: 'src/media/images/sprites/*.png',
    svg: 'src/media/svg/**/*.svg',
    videos: 'src/media/video/**/*.*',
  },
  watch: {
    nunj: ['src/media/**/*.nunj', 'global-data.json'],
    scripts: 'src/media/js/**/*.js',
    styles: 'src/media/**/*.{sass,scss}',
    images: 'src/media/images/**/*.*',
    fonts: 'src/media/fonts/**/*.*',
    sprites: 'src/media/images/sprites/*.png',
    svg: 'src/media/svg/**/*.svg',
    videos: 'src/media/video/**/*.*',
  },
  clean: 'build/',
};
